/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BringYourOwnWalletRouteImport } from './routes/bring-your-own-wallet'
import { Route as IndexRouteImport } from './routes/index'

const BringYourOwnWalletRoute = BringYourOwnWalletRouteImport.update({
  id: '/bring-your-own-wallet',
  path: '/bring-your-own-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bring-your-own-wallet': typeof BringYourOwnWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bring-your-own-wallet': typeof BringYourOwnWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bring-your-own-wallet': typeof BringYourOwnWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bring-your-own-wallet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bring-your-own-wallet'
  id: '__root__' | '/' | '/bring-your-own-wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BringYourOwnWalletRoute: typeof BringYourOwnWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bring-your-own-wallet': {
      id: '/bring-your-own-wallet'
      path: '/bring-your-own-wallet'
      fullPath: '/bring-your-own-wallet'
      preLoaderRoute: typeof BringYourOwnWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BringYourOwnWalletRoute: BringYourOwnWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
