/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbeddedWalletRouteImport } from './routes/embedded-wallet'
import { Route as IndexRouteImport } from './routes/index'

const EmbeddedWalletRoute = EmbeddedWalletRouteImport.update({
  id: '/embedded-wallet',
  path: '/embedded-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embedded-wallet': typeof EmbeddedWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embedded-wallet': typeof EmbeddedWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embedded-wallet': typeof EmbeddedWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embedded-wallet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embedded-wallet'
  id: '__root__' | '/' | '/embedded-wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbeddedWalletRoute: typeof EmbeddedWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embedded-wallet': {
      id: '/embedded-wallet'
      path: '/embedded-wallet'
      fullPath: '/embedded-wallet'
      preLoaderRoute: typeof EmbeddedWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbeddedWalletRoute: EmbeddedWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
